apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy
spec:
  params:
    - name: NAMESPACE
      type: string
    - name: IMAGE
      type: string
    - name: REPO_URL
      type: string
  steps:
    - name: kubectl-apply
      image: lachlanevenson/k8s-kubectl
      script: |
        apk add git
        git clone $(params.REPO_URL) /workspace/source
        kubectl apply -f /workspace/source/tekton/k8s/nginx-deployment.yml
    - name: kubectl-deploy
      image: lachlanevenson/k8s-kubectl
      script: |
        apk add git
        kubectl set image deployment/nginx-deployment nginx=$(params.IMAGE) -n=$(params.NAMESPACE)