apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: just-a-pod
  # TODO: 
  # - Add your nginx-pod spec with label `just-a-pod` and containerPort 80
spec:
  containers:
    - name: nginx-deployment
      image: nginx:latest
      ports:
        - containerPort: 80