apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
# TODO:
# - Add replicas
# - Add a selector that matches labels `just-a-pod`
# - Add a template for the nginx container used in `nginx-pod.yml`
  selector:
    matchLabels:
      app: just-a-pod
  replicas: 3
  template:
    metadata:
      labels:
        app: just-a-pod
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: just-a-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
